; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.30729.01 

	TITLE	d:\vice-players-master\Client\CScoreBoard.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

PUBLIC	?DisplayMode@@3U_D3DDISPLAYMODE@@A		; DisplayMode
_BSS	SEGMENT
?DisplayMode@@3U_D3DDISPLAYMODE@@A DB 010H DUP (?)	; DisplayMode
_BSS	ENDS
PUBLIC	?GetPing@CPlayerManager@@QAEHE@Z		; CPlayerManager::GetPing
PUBLIC	?GetScore@CPlayerManager@@QAEHE@Z		; CPlayerManager::GetScore
PUBLIC	?GetPlayerName@CPlayerManager@@QAEPADE@Z	; CPlayerManager::GetPlayerName
PUBLIC	?GetSlotState@CPlayerManager@@QAEHE@Z		; CPlayerManager::GetSlotState
PUBLIC	?GetLocalPlayerPing@CPlayerManager@@QAEHXZ	; CPlayerManager::GetLocalPlayerPing
PUBLIC	??_C@_02DPKJAMEF@?$CFd?$AA@			; `string'
PUBLIC	?GetLocalPlayerScore@CPlayerManager@@QAEHXZ	; CPlayerManager::GetLocalPlayerScore
PUBLIC	??_C@_02DKCKIIND@?$CFs?$AA@			; `string'
PUBLIC	?GetLocalPlayerName@CPlayerManager@@QAEPADXZ	; CPlayerManager::GetLocalPlayerName
PUBLIC	??_C@_04CPBFGEOK@Ping?$AA@			; `string'
PUBLIC	??_C@_05DGAPONBB@Score?$AA@			; `string'
PUBLIC	??_C@_06NPAAKFED@Player?$AA@			; `string'
PUBLIC	??_C@_0BL@JJIKEJIC@Vice?5City?3?5Players?5?9?5?$CFs?3?$CFs?$AA@ ; `string'
PUBLIC	__real@00000000
PUBLIC	?GetPlayerManager@CNetworkManager@@QAEPAVCPlayerManager@@XZ ; CNetworkManager::GetPlayerManager
PUBLIC	__$ArrayPad$
PUBLIC	?Draw@CScoreBoard@@QAEXXZ			; CScoreBoard::Draw
EXTRN	_free:PROC
EXTRN	?DrawTextA@CD3DFont@@QAEJMMKPBDKH@Z:PROC	; CD3DFont::DrawTextA
EXTRN	?GetTextExtent@CD3DFont@@QAEJPBDPAUtagSIZE@@M@Z:PROC ; CD3DFont::GetTextExtent
EXTRN	_sprintf:PROC
EXTRN	?tSettings@@3U_GAME_SETTINGS@@A:BYTE		; tSettings
EXTRN	?DrawBox@CD3DFont@@QAEJMMMMMK@Z:PROC		; CD3DFont::DrawBox
EXTRN	?pChatWindow@@3PAVCChatWindow@@A:DWORD		; pChatWindow
EXTRN	?pD3DDevice@@3PAUIDirect3DDevice8@@A:DWORD	; pD3DDevice
EXTRN	?UpdatePlayerScoresAndPings@CNetworkManager@@QAEXXZ:PROC ; CNetworkManager::UpdatePlayerScoresAndPings
EXTRN	_malloc:PROC
EXTRN	?pNetowkManager@@3PAVCNetworkManager@@A:DWORD	; pNetowkManager
EXTRN	___security_cookie:DWORD
EXTRN	__fltused:DWORD
EXTRN	@__security_check_cookie@4:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT ??_C@_02DPKJAMEF@?$CFd?$AA@
; File d:\vice-players-master\client\cscoreboard.cpp
CONST	SEGMENT
??_C@_02DPKJAMEF@?$CFd?$AA@ DB '%d', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_02DKCKIIND@?$CFs?$AA@
CONST	SEGMENT
??_C@_02DKCKIIND@?$CFs?$AA@ DB '%s', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_04CPBFGEOK@Ping?$AA@
CONST	SEGMENT
??_C@_04CPBFGEOK@Ping?$AA@ DB 'Ping', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_05DGAPONBB@Score?$AA@
CONST	SEGMENT
??_C@_05DGAPONBB@Score?$AA@ DB 'Score', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_06NPAAKFED@Player?$AA@
CONST	SEGMENT
??_C@_06NPAAKFED@Player?$AA@ DB 'Player', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BL@JJIKEJIC@Vice?5City?3?5Players?5?9?5?$CFs?3?$CFs?$AA@
CONST	SEGMENT
??_C@_0BL@JJIKEJIC@Vice?5City?3?5Players?5?9?5?$CFs?3?$CFs?$AA@ DB 'Vice '
	DB	'City: Players - %s:%s', 00H			; `string'
CONST	ENDS
;	COMDAT __real@00000000
CONST	SEGMENT
__real@00000000 DD 000000000r			; 0
CONST	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT ?Draw@CScoreBoard@@QAEXXZ
_TEXT	SEGMENT
tv423 = -580						; size = 8
tv419 = -572						; size = 8
tv745 = -564						; size = 8
tv710 = -564						; size = 8
tv675 = -564						; size = 8
tv635 = -564						; size = 8
tv602 = -564						; size = 8
tv569 = -564						; size = 8
tv536 = -564						; size = 8
tv509 = -564						; size = 8
tv482 = -564						; size = 8
tv455 = -564						; size = 8
tv415 = -564						; size = 8
tv735 = -556						; size = 8
tv700 = -556						; size = 8
tv665 = -556						; size = 8
tv625 = -556						; size = 8
tv592 = -556						; size = 8
tv559 = -556						; size = 8
tv526 = -556						; size = 8
tv499 = -556						; size = 8
tv472 = -556						; size = 8
tv446 = -556						; size = 8
tv411 = -556						; size = 8
_i$209290 = -349					; size = 1
_szPingTitleText$ = -340				; size = 4
_szScoreTitleText$ = -328				; size = 4
_szPlayerTitleText$ = -316				; size = 4
_szTitle$ = -304					; size = 128
_size$ = -168						; size = 8
_pFont$ = -152						; size = 4
_iCurrent$ = -140					; size = 4
_szPingText$ = -128					; size = 32
_szScoreText$ = -88					; size = 32
_szNameText$ = -48					; size = 4
_dwChatColor$ = -36					; size = 4
_pPlayerManager$ = -24					; size = 4
_this$ = -12						; size = 4
__$ArrayPad$ = -4					; size = 4
?Draw@CScoreBoard@@QAEXXZ PROC				; CScoreBoard::Draw, COMDAT
; _this$ = ecx

; 21   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 580				; 00000244H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-580]
	mov	ecx, 145				; 00000091H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	DWORD PTR _this$[ebp], ecx

; 22   : 	CPlayerManager* pPlayerManager = pNetowkManager->GetPlayerManager();

	mov	ecx, DWORD PTR ?pNetowkManager@@3PAVCNetworkManager@@A ; pNetowkManager
	call	?GetPlayerManager@CNetworkManager@@QAEPAVCPlayerManager@@XZ ; CNetworkManager::GetPlayerManager
	mov	DWORD PTR _pPlayerManager$[ebp], eax

; 23   : 	//DWORD dwNickColor;
; 24   : 	//char * szNick;
; 25   : 	DWORD dwChatColor = 0xFFFFFFFF;

	mov	DWORD PTR _dwChatColor$[ebp], -1

; 26   : 	char * szNameText = (char *)malloc(128);

	push	128					; 00000080H
	call	_malloc
	add	esp, 4
	mov	DWORD PTR _szNameText$[ebp], eax

; 27   : 	char szScoreText[32];
; 28   : 	char szPingText[32];
; 29   : 	int iCurrent = 0;

	mov	DWORD PTR _iCurrent$[ebp], 0

; 30   : 
; 31   : 	pNetowkManager->UpdatePlayerScoresAndPings();

	mov	ecx, DWORD PTR ?pNetowkManager@@3PAVCNetworkManager@@A ; pNetowkManager
	call	?UpdatePlayerScoresAndPings@CNetworkManager@@QAEXXZ ; CNetworkManager::UpdatePlayerScoresAndPings

; 32   : 
; 33   : 	pD3DDevice->GetDisplayMode(&DisplayMode);

	mov	esi, esp
	push	OFFSET ?DisplayMode@@3U_D3DDISPLAYMODE@@A ; DisplayMode
	mov	eax, DWORD PTR ?pD3DDevice@@3PAUIDirect3DDevice8@@A ; pD3DDevice
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR ?pD3DDevice@@3PAUIDirect3DDevice8@@A ; pD3DDevice
	push	edx
	mov	eax, DWORD PTR [ecx+32]
	call	eax
	cmp	esi, esp
	call	__RTC_CheckEsp

; 34   : 	// Get the d3d font pointer
; 35   : 	CD3DFont * pFont = pChatWindow->m_pD3DFont;

	mov	eax, DWORD PTR ?pChatWindow@@3PAVCChatWindow@@A ; pChatWindow
	mov	ecx, DWORD PTR [eax+968]
	mov	DWORD PTR _pFont$[ebp], ecx

; 36   : 
; 37   : 	// Draw the background
; 38   : 	pFont->DrawBox((float)(DisplayMode.Width / 4), (float)(DisplayMode.Height / 4), (float)(DisplayMode.Width / 2), (float)(DisplayMode.Height / 2), 0.0f, 0x50000000);

	push	1342177280				; 50000000H
	push	ecx
	fldz
	fstp	DWORD PTR [esp]
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	shr	eax, 1
	mov	DWORD PTR tv411[ebp], eax
	mov	DWORD PTR tv411[ebp+4], 0
	fild	QWORD PTR tv411[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	ecx, 1
	mov	DWORD PTR tv415[ebp], ecx
	mov	DWORD PTR tv415[ebp+4], 0
	fild	QWORD PTR tv415[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	edx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	shr	edx, 2
	mov	DWORD PTR tv419[ebp], edx
	mov	DWORD PTR tv419[ebp+4], 0
	fild	QWORD PTR tv419[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	eax, 2
	mov	DWORD PTR tv423[ebp], eax
	mov	DWORD PTR tv423[ebp+4], 0
	fild	QWORD PTR tv423[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?DrawBox@CD3DFont@@QAEJMMMMMK@Z		; CD3DFont::DrawBox

; 39   : 
; 40   : 	// Draw the title
; 41   : 	SIZE size;
; 42   : 	char szTitle[128];
; 43   : 	sprintf(szTitle, "Vice City: Players - %s:%s",  tSettings.szConnectHost,tSettings.szConnectPort);

	push	OFFSET ?tSettings@@3U_GAME_SETTINGS@@A+133
	push	OFFSET ?tSettings@@3U_GAME_SETTINGS@@A+4
	push	OFFSET ??_C@_0BL@JJIKEJIC@Vice?5City?3?5Players?5?9?5?$CFs?3?$CFs?$AA@
	lea	eax, DWORD PTR _szTitle$[ebp]
	push	eax
	call	_sprintf
	add	esp, 16					; 00000010H

; 44   : 	pFont->GetTextExtent(szTitle, &size);

	push	ecx
	fldz
	fstp	DWORD PTR [esp]
	lea	eax, DWORD PTR _size$[ebp]
	push	eax
	lea	ecx, DWORD PTR _szTitle$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?GetTextExtent@CD3DFont@@QAEJPBDPAUtagSIZE@@M@Z ; CD3DFont::GetTextExtent

; 45   : 	pFont->DrawText((float)((DisplayMode.Width / 2) - (size.cx / 2)), (float)((DisplayMode.Height / 4) + (DisplayMode.Height / 40)), 0xFFFFFFFF, szTitle);

	push	0
	push	0
	lea	eax, DWORD PTR _szTitle$[ebp]
	push	eax
	push	-1
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	shr	ecx, 2
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 40					; 00000028H
	div	esi
	add	ecx, eax
	mov	DWORD PTR tv446[ebp], ecx
	mov	DWORD PTR tv446[ebp+4], 0
	fild	QWORD PTR tv446[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	ecx, 1
	mov	eax, DWORD PTR _size$[ebp]
	cdq
	sub	eax, edx
	sar	eax, 1
	sub	ecx, eax
	mov	DWORD PTR tv455[ebp], ecx
	mov	DWORD PTR tv455[ebp+4], 0
	fild	QWORD PTR tv455[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?DrawTextA@CD3DFont@@QAEJMMKPBDKH@Z	; CD3DFont::DrawTextA

; 46   : 
; 47   : 	// Draw the player title
; 48   : 	const char * szPlayerTitleText = "Player";

	mov	DWORD PTR _szPlayerTitleText$[ebp], OFFSET ??_C@_06NPAAKFED@Player?$AA@

; 49   : 	pFont->GetTextExtent(szPlayerTitleText, &size);

	push	ecx
	fldz
	fstp	DWORD PTR [esp]
	lea	eax, DWORD PTR _size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _szPlayerTitleText$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?GetTextExtent@CD3DFont@@QAEJPBDPAUtagSIZE@@M@Z ; CD3DFont::GetTextExtent

; 50   : 	pFont->DrawText((float)(((DisplayMode.Width / 4) + (DisplayMode.Width / 8)) - (size.cx / 2)), (float)((DisplayMode.Height / 4) + (DisplayMode.Height / 20)), 0xFFFFFFFF, szPlayerTitleText);

	push	0
	push	0
	mov	eax, DWORD PTR _szPlayerTitleText$[ebp]
	push	eax
	push	-1
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	shr	ecx, 2
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 20					; 00000014H
	div	esi
	add	ecx, eax
	mov	DWORD PTR tv472[ebp], ecx
	mov	DWORD PTR tv472[ebp+4], 0
	fild	QWORD PTR tv472[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	ecx, 2
	mov	edx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	edx, 3
	add	ecx, edx
	mov	eax, DWORD PTR _size$[ebp]
	cdq
	sub	eax, edx
	sar	eax, 1
	sub	ecx, eax
	mov	DWORD PTR tv482[ebp], ecx
	mov	DWORD PTR tv482[ebp+4], 0
	fild	QWORD PTR tv482[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?DrawTextA@CD3DFont@@QAEJMMKPBDKH@Z	; CD3DFont::DrawTextA

; 51   : 
; 52   : 	// Draw the score title
; 53   : 	const char * szScoreTitleText = "Score";

	mov	DWORD PTR _szScoreTitleText$[ebp], OFFSET ??_C@_05DGAPONBB@Score?$AA@

; 54   : 	pFont->GetTextExtent(szScoreTitleText, &size);

	push	ecx
	fldz
	fstp	DWORD PTR [esp]
	lea	eax, DWORD PTR _size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _szScoreTitleText$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?GetTextExtent@CD3DFont@@QAEJPBDPAUtagSIZE@@M@Z ; CD3DFont::GetTextExtent

; 55   : 	pFont->DrawText((float)(((DisplayMode.Width / 4) + ((DisplayMode.Width / 8) * 2)) - (size.cx / 2)), (float)((DisplayMode.Height / 4) + (DisplayMode.Height / 20)), 0xFFFFFFFF, szScoreTitleText);

	push	0
	push	0
	mov	eax, DWORD PTR _szScoreTitleText$[ebp]
	push	eax
	push	-1
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	shr	ecx, 2
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 20					; 00000014H
	div	esi
	add	ecx, eax
	mov	DWORD PTR tv499[ebp], ecx
	mov	DWORD PTR tv499[ebp+4], 0
	fild	QWORD PTR tv499[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	edx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	edx, 2
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	eax, 3
	lea	ecx, DWORD PTR [edx+eax*2]
	mov	eax, DWORD PTR _size$[ebp]
	cdq
	sub	eax, edx
	sar	eax, 1
	sub	ecx, eax
	mov	DWORD PTR tv509[ebp], ecx
	mov	DWORD PTR tv509[ebp+4], 0
	fild	QWORD PTR tv509[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?DrawTextA@CD3DFont@@QAEJMMKPBDKH@Z	; CD3DFont::DrawTextA

; 56   : 
; 57   : 	// Draw the ping title
; 58   : 	const char * szPingTitleText = "Ping";

	mov	DWORD PTR _szPingTitleText$[ebp], OFFSET ??_C@_04CPBFGEOK@Ping?$AA@

; 59   : 	pFont->GetTextExtent(szPingTitleText, &size);

	push	ecx
	fldz
	fstp	DWORD PTR [esp]
	lea	eax, DWORD PTR _size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _szPingTitleText$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?GetTextExtent@CD3DFont@@QAEJPBDPAUtagSIZE@@M@Z ; CD3DFont::GetTextExtent

; 60   : 	pFont->DrawText((float)(((DisplayMode.Width / 4) + ((DisplayMode.Width / 8) * 3)) - (size.cx / 2)), (float)((DisplayMode.Height / 4) + (DisplayMode.Height / 20)), 0xFFFFFFFF, szPingTitleText);

	push	0
	push	0
	mov	eax, DWORD PTR _szPingTitleText$[ebp]
	push	eax
	push	-1
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	shr	ecx, 2
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 20					; 00000014H
	div	esi
	add	ecx, eax
	mov	DWORD PTR tv526[ebp], ecx
	mov	DWORD PTR tv526[ebp+4], 0
	fild	QWORD PTR tv526[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	ecx, 2
	mov	edx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	edx, 3
	imul	edx, 3
	add	ecx, edx
	mov	eax, DWORD PTR _size$[ebp]
	cdq
	sub	eax, edx
	sar	eax, 1
	sub	ecx, eax
	mov	DWORD PTR tv536[ebp], ecx
	mov	DWORD PTR tv536[ebp+4], 0
	fild	QWORD PTR tv536[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?DrawTextA@CD3DFont@@QAEJMMKPBDKH@Z	; CD3DFont::DrawTextA

; 61   : 
; 62   : 	// Format the local player name
; 63   : 	/*dwNickColor = pPlayerManager->GetLocalPlayer()->GetTeamColorAsARGB();
; 64   : 	szNick = pPlayerManager->GetLocalPlayerName();
; 65   : 	*szNameText = '\01'; szNameText++; // color start
; 66   : 	memcpy(szNameText, &dwNickColor, sizeof(DWORD)); szNameText += 4; // nick color
; 67   : 	memcpy(szNameText, szNick, strlen(szNick)); szNameText += strlen(szNick); // nick string
; 68   : 	*szNameText = '\01'; szNameText++; // color start
; 69   : 	memcpy(szNameText, &dwChatColor, sizeof(DWORD)); szNameText += 4; // chat color
; 70   : 	*szNameText = '\0';*/
; 71   : 	sprintf(szNameText, "%s", pPlayerManager->GetLocalPlayerName());

	mov	ecx, DWORD PTR _pPlayerManager$[ebp]
	call	?GetLocalPlayerName@CPlayerManager@@QAEPADXZ ; CPlayerManager::GetLocalPlayerName
	push	eax
	push	OFFSET ??_C@_02DKCKIIND@?$CFs?$AA@
	mov	eax, DWORD PTR _szNameText$[ebp]
	push	eax
	call	_sprintf
	add	esp, 12					; 0000000cH

; 72   : 
; 73   : 	// Draw the local player name
; 74   : 	pFont->GetTextExtent(szNameText, &size);

	push	ecx
	fldz
	fstp	DWORD PTR [esp]
	lea	eax, DWORD PTR _size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _szNameText$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?GetTextExtent@CD3DFont@@QAEJPBDPAUtagSIZE@@M@Z ; CD3DFont::GetTextExtent

; 75   : 	pFont->DrawText((float)(((DisplayMode.Width / 4) + (DisplayMode.Width / 8)) - (size.cx / 2)), (float)((DisplayMode.Height / 4) + (DisplayMode.Height / 14) + ((DisplayMode.Height / 60) * iCurrent)), 0xFFFFFFFF, szNameText);

	push	0
	push	0
	mov	eax, DWORD PTR _szNameText$[ebp]
	push	eax
	push	-1
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	shr	ecx, 2
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 14					; 0000000eH
	div	esi
	add	ecx, eax
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 60					; 0000003cH
	div	esi
	imul	eax, DWORD PTR _iCurrent$[ebp]
	add	ecx, eax
	mov	DWORD PTR tv559[ebp], ecx
	mov	DWORD PTR tv559[ebp+4], 0
	fild	QWORD PTR tv559[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	ecx, 2
	mov	edx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	edx, 3
	add	ecx, edx
	mov	eax, DWORD PTR _size$[ebp]
	cdq
	sub	eax, edx
	sar	eax, 1
	sub	ecx, eax
	mov	DWORD PTR tv569[ebp], ecx
	mov	DWORD PTR tv569[ebp+4], 0
	fild	QWORD PTR tv569[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?DrawTextA@CD3DFont@@QAEJMMKPBDKH@Z	; CD3DFont::DrawTextA

; 76   : 
; 77   : 	// Format the local player score
; 78   : 	sprintf(szScoreText, "%d", pPlayerManager->GetLocalPlayerScore());

	mov	ecx, DWORD PTR _pPlayerManager$[ebp]
	call	?GetLocalPlayerScore@CPlayerManager@@QAEHXZ ; CPlayerManager::GetLocalPlayerScore
	push	eax
	push	OFFSET ??_C@_02DPKJAMEF@?$CFd?$AA@
	lea	eax, DWORD PTR _szScoreText$[ebp]
	push	eax
	call	_sprintf
	add	esp, 12					; 0000000cH

; 79   : 
; 80   : 	// Draw the local player score
; 81   : 	pFont->GetTextExtent(szScoreText, &size);

	push	ecx
	fldz
	fstp	DWORD PTR [esp]
	lea	eax, DWORD PTR _size$[ebp]
	push	eax
	lea	ecx, DWORD PTR _szScoreText$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?GetTextExtent@CD3DFont@@QAEJPBDPAUtagSIZE@@M@Z ; CD3DFont::GetTextExtent

; 82   : 	pFont->DrawText((float)(((DisplayMode.Width / 4) + ((DisplayMode.Width / 8) * 2)) - (size.cx / 2)), (float)((DisplayMode.Height / 4) + (DisplayMode.Height / 14) + ((DisplayMode.Height / 60) * iCurrent)), 0xFFFFFFFF, szScoreText);

	push	0
	push	0
	lea	eax, DWORD PTR _szScoreText$[ebp]
	push	eax
	push	-1
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	shr	ecx, 2
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 14					; 0000000eH
	div	esi
	add	ecx, eax
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 60					; 0000003cH
	div	esi
	imul	eax, DWORD PTR _iCurrent$[ebp]
	add	ecx, eax
	mov	DWORD PTR tv592[ebp], ecx
	mov	DWORD PTR tv592[ebp+4], 0
	fild	QWORD PTR tv592[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	edx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	edx, 2
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	eax, 3
	lea	ecx, DWORD PTR [edx+eax*2]
	mov	eax, DWORD PTR _size$[ebp]
	cdq
	sub	eax, edx
	sar	eax, 1
	sub	ecx, eax
	mov	DWORD PTR tv602[ebp], ecx
	mov	DWORD PTR tv602[ebp+4], 0
	fild	QWORD PTR tv602[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?DrawTextA@CD3DFont@@QAEJMMKPBDKH@Z	; CD3DFont::DrawTextA

; 83   : 
; 84   : 	// Format the local player ping
; 85   : 	sprintf(szPingText, "%d", pPlayerManager->GetLocalPlayerPing());

	mov	ecx, DWORD PTR _pPlayerManager$[ebp]
	call	?GetLocalPlayerPing@CPlayerManager@@QAEHXZ ; CPlayerManager::GetLocalPlayerPing
	push	eax
	push	OFFSET ??_C@_02DPKJAMEF@?$CFd?$AA@
	lea	eax, DWORD PTR _szPingText$[ebp]
	push	eax
	call	_sprintf
	add	esp, 12					; 0000000cH

; 86   : 
; 87   : 	// Draw the local player ping
; 88   : 	pFont->GetTextExtent(szPingText, &size);

	push	ecx
	fldz
	fstp	DWORD PTR [esp]
	lea	eax, DWORD PTR _size$[ebp]
	push	eax
	lea	ecx, DWORD PTR _szPingText$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?GetTextExtent@CD3DFont@@QAEJPBDPAUtagSIZE@@M@Z ; CD3DFont::GetTextExtent

; 89   : 	pFont->DrawText((float)(((DisplayMode.Width / 4) + ((DisplayMode.Width / 8) * 3)) - (size.cx / 2)), (float)((DisplayMode.Height / 4) + (DisplayMode.Height / 14) + ((DisplayMode.Height / 60) * iCurrent)), 0xFFFFFFFF, szPingText);

	push	0
	push	0
	lea	eax, DWORD PTR _szPingText$[ebp]
	push	eax
	push	-1
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	shr	ecx, 2
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 14					; 0000000eH
	div	esi
	add	ecx, eax
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 60					; 0000003cH
	div	esi
	imul	eax, DWORD PTR _iCurrent$[ebp]
	add	ecx, eax
	mov	DWORD PTR tv625[ebp], ecx
	mov	DWORD PTR tv625[ebp+4], 0
	fild	QWORD PTR tv625[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	ecx, 2
	mov	edx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	edx, 3
	imul	edx, 3
	add	ecx, edx
	mov	eax, DWORD PTR _size$[ebp]
	cdq
	sub	eax, edx
	sar	eax, 1
	sub	ecx, eax
	mov	DWORD PTR tv635[ebp], ecx
	mov	DWORD PTR tv635[ebp+4], 0
	fild	QWORD PTR tv635[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?DrawTextA@CD3DFont@@QAEJMMKPBDKH@Z	; CD3DFont::DrawTextA

; 90   : 
; 91   : 	iCurrent ++;

	mov	eax, DWORD PTR _iCurrent$[ebp]
	add	eax, 1
	mov	DWORD PTR _iCurrent$[ebp], eax

; 92   : 
; 93   : 	for(BYTE i = 0; i < MAX_PLAYERS; i++) {

	mov	BYTE PTR _i$209290[ebp], 0
	jmp	SHORT $LN4@Draw
$LN3@Draw:
	mov	al, BYTE PTR _i$209290[ebp]
	add	al, 1
	mov	BYTE PTR _i$209290[ebp], al
$LN4@Draw:
	movzx	eax, BYTE PTR _i$209290[ebp]
	cmp	eax, 50					; 00000032H
	jge	$LN2@Draw

; 94   : 		if(pPlayerManager->GetSlotState(i)) {

	movzx	eax, BYTE PTR _i$209290[ebp]
	push	eax
	mov	ecx, DWORD PTR _pPlayerManager$[ebp]
	call	?GetSlotState@CPlayerManager@@QAEHE@Z	; CPlayerManager::GetSlotState
	test	eax, eax
	je	$LN1@Draw

; 95   : 			// Format the player name
; 96   : 			/*dwNickColor = pPlayerManager->GetAt(i)->GetTeamColorAsARGB();
; 97   : 			szNick = pPlayerManager->GetPlayerName(i);
; 98   : 			*szNameText = '\01'; szNameText++; // color start
; 99   : 			memcpy(szNameText, &dwNickColor, sizeof(DWORD)); szNameText += 4; // nick color
; 100  : 			memcpy(szNameText, szNick, strlen(szNick)); szNameText += strlen(szNick); // nick string
; 101  : 			*szNameText = '\01'; szNameText++; // color start
; 102  : 			memcpy(szNameText, &dwChatColor, sizeof(DWORD)); szNameText += 4; // chat color
; 103  : 			*szNameText = '\0';*/
; 104  : 			sprintf(szNameText, "%s", pPlayerManager->GetPlayerName(i));

	movzx	eax, BYTE PTR _i$209290[ebp]
	push	eax
	mov	ecx, DWORD PTR _pPlayerManager$[ebp]
	call	?GetPlayerName@CPlayerManager@@QAEPADE@Z ; CPlayerManager::GetPlayerName
	push	eax
	push	OFFSET ??_C@_02DKCKIIND@?$CFs?$AA@
	mov	ecx, DWORD PTR _szNameText$[ebp]
	push	ecx
	call	_sprintf
	add	esp, 12					; 0000000cH

; 105  : 
; 106  : 			// Draw the player name
; 107  : 			pFont->GetTextExtent(szNameText, &size);

	push	ecx
	fldz
	fstp	DWORD PTR [esp]
	lea	eax, DWORD PTR _size$[ebp]
	push	eax
	mov	ecx, DWORD PTR _szNameText$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?GetTextExtent@CD3DFont@@QAEJPBDPAUtagSIZE@@M@Z ; CD3DFont::GetTextExtent

; 108  : 			pFont->DrawText((float)(((DisplayMode.Width / 4) + (DisplayMode.Width / 8)) - (size.cx / 2)), (float)((DisplayMode.Height / 4) + (DisplayMode.Height / 14) + ((DisplayMode.Height / 60) * iCurrent)), 0xFFFFFFFF, szNameText);

	push	0
	push	0
	mov	eax, DWORD PTR _szNameText$[ebp]
	push	eax
	push	-1
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	shr	ecx, 2
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 14					; 0000000eH
	div	esi
	add	ecx, eax
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 60					; 0000003cH
	div	esi
	imul	eax, DWORD PTR _iCurrent$[ebp]
	add	ecx, eax
	mov	DWORD PTR tv665[ebp], ecx
	mov	DWORD PTR tv665[ebp+4], 0
	fild	QWORD PTR tv665[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	ecx, 2
	mov	edx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	edx, 3
	add	ecx, edx
	mov	eax, DWORD PTR _size$[ebp]
	cdq
	sub	eax, edx
	sar	eax, 1
	sub	ecx, eax
	mov	DWORD PTR tv675[ebp], ecx
	mov	DWORD PTR tv675[ebp+4], 0
	fild	QWORD PTR tv675[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?DrawTextA@CD3DFont@@QAEJMMKPBDKH@Z	; CD3DFont::DrawTextA

; 109  : 
; 110  : 			// Format the player score
; 111  : 			sprintf(szScoreText, "%d", pPlayerManager->GetScore(i));

	movzx	eax, BYTE PTR _i$209290[ebp]
	push	eax
	mov	ecx, DWORD PTR _pPlayerManager$[ebp]
	call	?GetScore@CPlayerManager@@QAEHE@Z	; CPlayerManager::GetScore
	push	eax
	push	OFFSET ??_C@_02DPKJAMEF@?$CFd?$AA@
	lea	ecx, DWORD PTR _szScoreText$[ebp]
	push	ecx
	call	_sprintf
	add	esp, 12					; 0000000cH

; 112  : 
; 113  : 			// Draw the player score
; 114  : 			pFont->GetTextExtent(szScoreText, &size);

	push	ecx
	fldz
	fstp	DWORD PTR [esp]
	lea	eax, DWORD PTR _size$[ebp]
	push	eax
	lea	ecx, DWORD PTR _szScoreText$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?GetTextExtent@CD3DFont@@QAEJPBDPAUtagSIZE@@M@Z ; CD3DFont::GetTextExtent

; 115  : 			pFont->DrawText((float)(((DisplayMode.Width / 4) + ((DisplayMode.Width / 8) * 2)) - (size.cx / 2)), (float)((DisplayMode.Height / 4) + (DisplayMode.Height / 14) + ((DisplayMode.Height / 60) * iCurrent)), 0xFFFFFFFF, szScoreText);

	push	0
	push	0
	lea	eax, DWORD PTR _szScoreText$[ebp]
	push	eax
	push	-1
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	shr	ecx, 2
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 14					; 0000000eH
	div	esi
	add	ecx, eax
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 60					; 0000003cH
	div	esi
	imul	eax, DWORD PTR _iCurrent$[ebp]
	add	ecx, eax
	mov	DWORD PTR tv700[ebp], ecx
	mov	DWORD PTR tv700[ebp+4], 0
	fild	QWORD PTR tv700[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	edx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	edx, 2
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	eax, 3
	lea	ecx, DWORD PTR [edx+eax*2]
	mov	eax, DWORD PTR _size$[ebp]
	cdq
	sub	eax, edx
	sar	eax, 1
	sub	ecx, eax
	mov	DWORD PTR tv710[ebp], ecx
	mov	DWORD PTR tv710[ebp+4], 0
	fild	QWORD PTR tv710[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?DrawTextA@CD3DFont@@QAEJMMKPBDKH@Z	; CD3DFont::DrawTextA

; 116  : 
; 117  : 			// Format the player ping
; 118  : 			sprintf(szPingText, "%d", pPlayerManager->GetPing(i));

	movzx	eax, BYTE PTR _i$209290[ebp]
	push	eax
	mov	ecx, DWORD PTR _pPlayerManager$[ebp]
	call	?GetPing@CPlayerManager@@QAEHE@Z	; CPlayerManager::GetPing
	push	eax
	push	OFFSET ??_C@_02DPKJAMEF@?$CFd?$AA@
	lea	ecx, DWORD PTR _szPingText$[ebp]
	push	ecx
	call	_sprintf
	add	esp, 12					; 0000000cH

; 119  : 
; 120  : 			// Draw the player ping
; 121  : 			pFont->GetTextExtent(szPingText, &size);

	push	ecx
	fldz
	fstp	DWORD PTR [esp]
	lea	eax, DWORD PTR _size$[ebp]
	push	eax
	lea	ecx, DWORD PTR _szPingText$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?GetTextExtent@CD3DFont@@QAEJPBDPAUtagSIZE@@M@Z ; CD3DFont::GetTextExtent

; 122  : 			pFont->DrawText((float)(((DisplayMode.Width / 4) + ((DisplayMode.Width / 8) * 3)) - (size.cx / 2)), (float)((DisplayMode.Height / 4) + (DisplayMode.Height / 14) + ((DisplayMode.Height / 60) * iCurrent)), 0xFFFFFFFF, szPingText);

	push	0
	push	0
	lea	eax, DWORD PTR _szPingText$[ebp]
	push	eax
	push	-1
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	shr	ecx, 2
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 14					; 0000000eH
	div	esi
	add	ecx, eax
	mov	eax, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A+4
	xor	edx, edx
	mov	esi, 60					; 0000003cH
	div	esi
	imul	eax, DWORD PTR _iCurrent$[ebp]
	add	ecx, eax
	mov	DWORD PTR tv735[ebp], ecx
	mov	DWORD PTR tv735[ebp+4], 0
	fild	QWORD PTR tv735[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	ecx, 2
	mov	edx, DWORD PTR ?DisplayMode@@3U_D3DDISPLAYMODE@@A
	shr	edx, 3
	imul	edx, 3
	add	ecx, edx
	mov	eax, DWORD PTR _size$[ebp]
	cdq
	sub	eax, edx
	sar	eax, 1
	sub	ecx, eax
	mov	DWORD PTR tv745[ebp], ecx
	mov	DWORD PTR tv745[ebp+4], 0
	fild	QWORD PTR tv745[ebp]
	push	ecx
	fstp	DWORD PTR [esp]
	mov	ecx, DWORD PTR _pFont$[ebp]
	call	?DrawTextA@CD3DFont@@QAEJMMKPBDKH@Z	; CD3DFont::DrawTextA

; 123  : 
; 124  : 			iCurrent++;

	mov	eax, DWORD PTR _iCurrent$[ebp]
	add	eax, 1
	mov	DWORD PTR _iCurrent$[ebp], eax
$LN1@Draw:

; 125  : 		}
; 126  : 	}

	jmp	$LN3@Draw
$LN2@Draw:

; 127  : 
; 128  : 	free(szNameText);

	mov	eax, DWORD PTR _szNameText$[ebp]
	push	eax
	call	_free
	add	esp, 4

; 129  : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN12@Draw
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 580				; 00000244H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN12@Draw:
	DD	4
	DD	$LN11@Draw
$LN11@Draw:
	DD	-88					; ffffffa8H
	DD	32					; 00000020H
	DD	$LN7@Draw
	DD	-128					; ffffff80H
	DD	32					; 00000020H
	DD	$LN8@Draw
	DD	-168					; ffffff58H
	DD	8
	DD	$LN9@Draw
	DD	-304					; fffffed0H
	DD	128					; 00000080H
	DD	$LN10@Draw
$LN10@Draw:
	DB	115					; 00000073H
	DB	122					; 0000007aH
	DB	84					; 00000054H
	DB	105					; 00000069H
	DB	116					; 00000074H
	DB	108					; 0000006cH
	DB	101					; 00000065H
	DB	0
$LN9@Draw:
	DB	115					; 00000073H
	DB	105					; 00000069H
	DB	122					; 0000007aH
	DB	101					; 00000065H
	DB	0
$LN8@Draw:
	DB	115					; 00000073H
	DB	122					; 0000007aH
	DB	80					; 00000050H
	DB	105					; 00000069H
	DB	110					; 0000006eH
	DB	103					; 00000067H
	DB	84					; 00000054H
	DB	101					; 00000065H
	DB	120					; 00000078H
	DB	116					; 00000074H
	DB	0
$LN7@Draw:
	DB	115					; 00000073H
	DB	122					; 0000007aH
	DB	83					; 00000053H
	DB	99					; 00000063H
	DB	111					; 0000006fH
	DB	114					; 00000072H
	DB	101					; 00000065H
	DB	84					; 00000054H
	DB	101					; 00000065H
	DB	120					; 00000078H
	DB	116					; 00000074H
	DB	0
?Draw@CScoreBoard@@QAEXXZ ENDP				; CScoreBoard::Draw
; Function compile flags: /Odtp /RTCsu /ZI
; File d:\vice-players-master\client\net\cplayermanager.h
_TEXT	ENDS
;	COMDAT ?GetLocalPlayerName@CPlayerManager@@QAEPADXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?GetLocalPlayerName@CPlayerManager@@QAEPADXZ PROC	; CPlayerManager::GetLocalPlayerName, COMDAT
; _this$ = ecx

; 36   : 	char * GetLocalPlayerName() { return m_szLocalPlayerName; };

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	add	eax, 408				; 00000198H
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?GetLocalPlayerName@CPlayerManager@@QAEPADXZ ENDP	; CPlayerManager::GetLocalPlayerName
; Function compile flags: /Odtp /RTCsu /ZI
_TEXT	ENDS
;	COMDAT ?GetPlayerName@CPlayerManager@@QAEPADE@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_playerID$ = 8						; size = 1
?GetPlayerName@CPlayerManager@@QAEPADE@Z PROC		; CPlayerManager::GetPlayerName, COMDAT
; _this$ = ecx

; 37   : 	char * GetPlayerName(EntityId playerID) { return m_szPlayerNames[playerID]; };

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	movzx	eax, BYTE PTR _playerID$[ebp]
	imul	eax, 25					; 00000019H
	mov	ecx, DWORD PTR _this$[ebp]
	lea	eax, DWORD PTR [ecx+eax+433]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
?GetPlayerName@CPlayerManager@@QAEPADE@Z ENDP		; CPlayerManager::GetPlayerName
; Function compile flags: /Odtp /RTCsu /ZI
_TEXT	ENDS
;	COMDAT ?GetSlotState@CPlayerManager@@QAEHE@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_playerID$ = 8						; size = 1
?GetSlotState@CPlayerManager@@QAEHE@Z PROC		; CPlayerManager::GetSlotState, COMDAT
; _this$ = ecx

; 50   : 	BOOL GetSlotState(EntityId playerID) {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 51   : 		if(playerID > MAX_PLAYERS) { return FALSE; }

	movzx	eax, BYTE PTR _playerID$[ebp]
	cmp	eax, 50					; 00000032H
	jle	SHORT $LN1@GetSlotSta
	xor	eax, eax
	jmp	SHORT $LN2@GetSlotSta
$LN1@GetSlotSta:

; 52   : 		return m_bPlayerSlotState[playerID];

	movzx	eax, BYTE PTR _playerID$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [ecx+eax*4]
$LN2@GetSlotSta:

; 53   : 	};

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
?GetSlotState@CPlayerManager@@QAEHE@Z ENDP		; CPlayerManager::GetSlotState
; Function compile flags: /Odtp /RTCsu /ZI
_TEXT	ENDS
;	COMDAT ?GetPing@CPlayerManager@@QAEHE@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_playerID$ = 8						; size = 1
?GetPing@CPlayerManager@@QAEHE@Z PROC			; CPlayerManager::GetPing, COMDAT
; _this$ = ecx

; 80   : 	int GetPing(EntityId playerID) { return m_iPing[playerID]; };

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	movzx	eax, BYTE PTR _playerID$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [ecx+eax*4+2092]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
?GetPing@CPlayerManager@@QAEHE@Z ENDP			; CPlayerManager::GetPing
; Function compile flags: /Odtp /RTCsu /ZI
_TEXT	ENDS
;	COMDAT ?GetScore@CPlayerManager@@QAEHE@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_playerID$ = 8						; size = 1
?GetScore@CPlayerManager@@QAEHE@Z PROC			; CPlayerManager::GetScore, COMDAT
; _this$ = ecx

; 81   : 	int GetScore(EntityId playerID) { return m_iScore[playerID]; };

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	movzx	eax, BYTE PTR _playerID$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [ecx+eax*4+1892]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
?GetScore@CPlayerManager@@QAEHE@Z ENDP			; CPlayerManager::GetScore
; Function compile flags: /Odtp /RTCsu /ZI
_TEXT	ENDS
;	COMDAT ?GetLocalPlayerPing@CPlayerManager@@QAEHXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?GetLocalPlayerPing@CPlayerManager@@QAEHXZ PROC		; CPlayerManager::GetLocalPlayerPing, COMDAT
; _this$ = ecx

; 82   : 	int GetLocalPlayerPing() { return m_iLocalPlayerPing; };

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+1888]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?GetLocalPlayerPing@CPlayerManager@@QAEHXZ ENDP		; CPlayerManager::GetLocalPlayerPing
; Function compile flags: /Odtp /RTCsu /ZI
_TEXT	ENDS
;	COMDAT ?GetLocalPlayerScore@CPlayerManager@@QAEHXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?GetLocalPlayerScore@CPlayerManager@@QAEHXZ PROC	; CPlayerManager::GetLocalPlayerScore, COMDAT
; _this$ = ecx

; 83   : 	int GetLocalPlayerScore() { return m_iLocalPlayerScore; };

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+1884]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?GetLocalPlayerScore@CPlayerManager@@QAEHXZ ENDP	; CPlayerManager::GetLocalPlayerScore
; Function compile flags: /Odtp /RTCsu /ZI
; File d:\vice-players-master\client\net\cnetworkmanager.h
_TEXT	ENDS
;	COMDAT ?GetPlayerManager@CNetworkManager@@QAEPAVCPlayerManager@@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?GetPlayerManager@CNetworkManager@@QAEPAVCPlayerManager@@XZ PROC ; CNetworkManager::GetPlayerManager, COMDAT
; _this$ = ecx

; 79   : 	CPlayerManager * GetPlayerManager() { return m_pPlayerManager; };

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?GetPlayerManager@CNetworkManager@@QAEPAVCPlayerManager@@XZ ENDP ; CNetworkManager::GetPlayerManager
_TEXT	ENDS
END
